const app=document.getElementById('questionnaire-app');
const params=new URLSearchParams(location.search),token=params.get('token')||'',base=(params.get('url')||'').replace(/\/+$/,''),key=params.get('key')||'';
let schema=null,current=null;
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function rpc(name,body){if(!base||!key||!token)throw new Error('Lien incomplet. Demandez un nouveau lien au technicien.');const r=await fetch(`${base}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:key,'Content-Type':'application/json'},body:JSON.stringify(body)}),t=await r.text();let d=null;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw new Error(d?.message||d?.hint||String(d)||`Erreur ${r.status}`);return d}
function inputHtml(q,a={}){const val=a.value??'',comment=a.comment??'';let h='';if(q.type==='select'||q.type==='availability'){h=`<select data-q-value="${esc(q.id)}"><option value="">Choisir…</option>${(q.options||[]).map(x=>`<option value="${esc(x)}" ${val===x?'selected':''}>${esc(x)}</option>`).join('')}</select>`}else if(q.type==='multi'){const values=Array.isArray(a.values)?a.values:[];h=`<div class="choices">${(q.options||[]).map(x=>`<label><input type="checkbox" data-q-multi="${esc(q.id)}" value="${esc(x)}" ${values.includes(x)?'checked':''}>${esc(x)}</label>`).join('')}</div>`}else if(q.type==='number'){h=`<div class="row"><input inputmode="decimal" data-q-value="${esc(q.id)}" value="${esc(val)}" placeholder="Valeur">${q.unit?`<input value="${esc(q.unit)}" disabled>`:''}</div>`}else if(q.type==='textarea'){h=`<textarea data-q-value="${esc(q.id)}" placeholder="Votre réponse">${esc(val)}</textarea>`}else{h=`<input data-q-value="${esc(q.id)}" value="${esc(val)}" placeholder="Votre réponse">`}
  if(q.comment!==false)h+=`<textarea data-q-comment="${esc(q.id)}" placeholder="Précision / commentaire facultatif">${esc(comment)}</textarea>`;
  if(Array.isArray(q.extraFields)&&q.extraFields.length)h+=`<div class="row">${q.extraFields.map(f=>`<div><label class="help">${esc(f.label)}</label><input type="${f.type==='date'?'date':'text'}" data-q-extra="${esc(q.id)}" data-extra-id="${esc(f.id)}" value="${esc(a.extras?.[f.id]||'')}"></div>`).join('')}</div>`;
  if(q.fileAllowed)h+=`<div class="attachment-box"><label>Joindre un document ou une photo (facultatif)</label><input type="file" data-q-file="${esc(q.id)}" accept="image/*,.pdf,application/pdf" multiple><div class="file-note">Maximum 2 Mo par fichier, 6 Mo au total.</div><div class="attachment-list" data-q-files-list="${esc(q.id)}"></div></div>`;
  return h;
}
function render(){const qd=current||{};schema=qd.schema;if(!schema)return app.innerHTML='<div class="error">Questionnaire introuvable.</div>';const response=qd.response||{};app.innerHTML=`<section class="card hero"><h2>${esc(schema.title)}</h2><div class="muted">${esc(schema.farmName)}${schema.visitDate?` · visite du ${new Date(schema.visitDate+'T12:00:00').toLocaleDateString('fr-FR')}`:''}</div><div class="notice">${esc(schema.intro||'Merci de compléter les éléments ci-dessous.')}</div></section><form id="farmer-form">${(schema.sections||[]).map(sec=>`<section class="card section"><h3>${esc(sec.title)}</h3>${sec.intro?`<p class="muted">${esc(sec.intro)}</p>`:''}${(sec.questions||[]).map(q=>`<div class="question" data-question="${esc(q.id)}"><label>${esc(q.label)}</label>${q.help?`<div class="help">${esc(q.help)}</div>`:''}${inputHtml(q,response.answers?.[q.id]||{})}</div>`).join('')}</section>`).join('')}<section class="card"><label>Autre information utile pour préparer ou compléter la visite</label><textarea id="general-comment" placeholder="Vous pouvez ajouter ici une information qui ne figure pas dans le questionnaire.">${esc(response.generalComment||'')}</textarea></section><button class="primary" type="submit">Envoyer mes réponses</button></form>`;bindFiles();document.getElementById('farmer-form').onsubmit=submit}
const fileStore={};
function bindFiles(){document.querySelectorAll('[data-q-file]').forEach(inp=>inp.onchange=async()=>{const id=inp.dataset.qFile,files=[...inp.files],list=document.querySelector(`[data-q-files-list="${CSS.escape(id)}"]`);let total=Object.values(fileStore).flat().reduce((n,f)=>n+(f.size||0),0);for(const f of files){if(f.size>2*1024*1024){alert(`${f.name} dépasse 2 Mo.`);continue}if(total+f.size>6*1024*1024){alert('Le total des pièces jointes dépasse 6 Mo.');break}const dataUrl=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(f)});fileStore[id]=fileStore[id]||[];fileStore[id].push({fileName:f.name,mimeType:f.type||'application/octet-stream',size:f.size,dataUrl});total+=f.size}list.innerHTML=(fileStore[id]||[]).map(f=>`<span>📎 ${esc(f.fileName)}</span>`).join('')})}
function collect(){const answers={};for(const sec of schema.sections||[])for(const q of sec.questions||[]){const entry={};const value=document.querySelector(`[data-q-value="${CSS.escape(q.id)}"]`);if(value)entry.value=value.value;const multis=[...document.querySelectorAll(`[data-q-multi="${CSS.escape(q.id)}"]:checked`)];if(multis.length)entry.values=multis.map(x=>x.value);const comment=document.querySelector(`[data-q-comment="${CSS.escape(q.id)}"]`);if(comment)entry.comment=comment.value;const extras={};document.querySelectorAll(`[data-q-extra="${CSS.escape(q.id)}"]`).forEach(x=>{if(x.value)extras[x.dataset.extraId]=x.value});if(Object.keys(extras).length)entry.extras=extras;if(fileStore[q.id]?.length)entry.attachments=fileStore[q.id];if(entry.value||entry.comment||entry.values?.length||entry.attachments?.length||entry.extras)answers[q.id]=entry}return {answers,generalComment:document.getElementById('general-comment')?.value||'',submittedAt:new Date().toISOString(),userAgent:navigator.userAgent}}
async function submit(e){e.preventDefault();const btn=e.submitter;btn.disabled=true;btn.textContent='Envoi en cours…';try{const response=collect();await rpc('submit_farmer_questionnaire',{p_token:token,p_response:response});app.innerHTML='<section class="card success"><strong>✓ Réponses envoyées</strong><p>Merci. Le technicien pourra les vérifier et les intégrer à la visite.</p><p>Vous pouvez fermer cette page.</p></section>'}catch(err){btn.disabled=false;btn.textContent='Envoyer mes réponses';alert(`Envoi impossible : ${err.message}`)}}
(async()=>{try{current=await rpc('fetch_farmer_questionnaire',{p_token:token});if(current?.error)throw new Error(current.error);render()}catch(e){app.innerHTML=`<div class="error"><strong>Questionnaire inaccessible</strong><br>${esc(e.message)}</div>`}})();
