const CACHE = 'audit-bovin-v14.6.20';
const ASSETS = ['./?v=14.6.20','./index.html?v=14.6.20','./styles.css?v=14.6.20','./app.js?v=14.6.20','./cloud-sync.js?v=14.6.20','./analysis-rules.js','./knowledge-base.js','./storage.js','./utils.js','./manifest.webmanifest?v=14.6.20','./icon-192.png?v=14.6.20','./icon-512.png?v=14.6.20','./planches-visuelles.png','./jszip.min.js?v=14.6.20','./modele-partenaires-passage-bv.xlsx?v=14.6.20','./memo-aplombs.jpeg','./memo-srr.jpeg','./memo-nec.jpeg','./library-pdfs/outil-apera-ph5f.pdf','./library-pdfs/outil-control-th.pdf','./library-pdfs/outil-extech-ph100.pdf','./library-pdfs/outil-extech-re300.pdf','./library-pdfs/outil-freestyle-optium.pdf','./library-pdfs/outil-hanna-hi701.pdf','./library-pdfs/outil-laquatwin-4m.pdf','./library-pdfs/outil-lysun-uree.pdf','./library-pdfs/outil-multimetre.pdf','./library-pdfs/theme-approche-globale.pdf','./library-pdfs/theme-eau-abreuvement.pdf','./library-pdfs/theme-feces-digestion.pdf','./library-pdfs/theme-fourrages-alimentation.pdf','./library-pdfs/theme-lait-colostrum-veaux.pdf','./library-pdfs/theme-litiere-environnement.pdf','./library-pdfs/theme-observation-troupeau.pdf','./library-pdfs/theme-outils-prelevements.pdf','./library-pdfs/theme-plantes-paturage.pdf','./library-pdfs/theme-sang.pdf','./library-pdfs/theme-sol.pdf','./library-pdfs/theme-urines.pdf','./library-thumbs/outil-apera-ph5f.jpg','./library-thumbs/outil-control-th.jpg','./library-thumbs/outil-extech-ph100.jpg','./library-thumbs/outil-extech-re300.jpg','./library-thumbs/outil-freestyle-optium.jpg','./library-thumbs/outil-hanna-hi701.jpg','./library-thumbs/outil-laquatwin-4m.jpg','./library-thumbs/outil-lysun-uree.jpg','./library-thumbs/outil-multimetre.jpg','./library-thumbs/theme-approche-globale.jpg','./library-thumbs/theme-eau-abreuvement.jpg','./library-thumbs/theme-feces-digestion.jpg','./library-thumbs/theme-fourrages-alimentation.jpg','./library-thumbs/theme-lait-colostrum-veaux.jpg','./library-thumbs/theme-litiere-environnement.jpg','./library-thumbs/theme-observation-troupeau.jpg','./library-thumbs/theme-outils-prelevements.jpg','./library-thumbs/theme-plantes-paturage.jpg','./library-thumbs/theme-sang.jpg','./library-thumbs/theme-sol.jpg','./library-thumbs/theme-urines.jpg'];
self.addEventListener('install', event => event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(ASSETS)).then(() => self.skipWaiting())));
self.addEventListener('activate', event => event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(key => key !== CACHE).map(key => caches.delete(key)))).then(() => self.clients.claim())));
self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET') return;
  event.respondWith(fetch(event.request).then(response => {
    if (!response || !response.ok) throw new Error('Réponse réseau invalide');
    const copy = response.clone();
    caches.open(CACHE).then(cache => cache.put(event.request, copy));
    return response;
  }).catch(() => caches.match(event.request).then(hit => hit || caches.match('./index.html'))));
});
